name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile windows_graphs.cpp
      run: g++ -std=c++17 -o main windows_graphs.cpp

    - name: Run the compiled binary
      run: ./main
